#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LLM_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
AGENTS_DIR="$LLM_DIR/agents"

OPENCODE_AGENTS_DIR="${OPENCODE_AGENTS_DIR:-$HOME/.config/opencode/agents}"
CLAUDE_AGENTS_DIR="${CLAUDE_AGENTS_DIR:-$HOME/.claude/agents}"
CODEX_AGENTS_DIR="${CODEX_AGENTS_DIR:-$HOME/.codex/agents}"

mkdir -p "$OPENCODE_AGENTS_DIR" "$CLAUDE_AGENTS_DIR" "$CODEX_AGENTS_DIR"

managed_header() {
  printf '# Generated by dotfiles llm/scripts/render-agent-targets.sh; edit llm/agents/*.md instead.\n'
}

can_write_generated() {
  dest="$1"
  if [ ! -e "$dest" ] && [ ! -L "$dest" ]; then
    return 0
  fi

  if [ -f "$dest" ] && IFS= read -r first_line < "$dest" && [ "$first_line" = "# Generated by dotfiles llm/scripts/render-agent-targets.sh; edit llm/agents/*.md instead." ]; then
    return 0
  fi

  echo "Skipping unmanaged existing agent file: $dest" >&2
  return 1
}

parse_agent() {
  file="$1"
  name=""
  description=""
  mode=""
  model_class=""
  body=""
  in_frontmatter=0
  frontmatter_done=0

  while IFS= read -r line || [ -n "$line" ]; do
    if [ "$frontmatter_done" -eq 0 ]; then
      if [ "$line" = "---" ]; then
        if [ "$in_frontmatter" -eq 0 ]; then
          in_frontmatter=1
        else
          frontmatter_done=1
        fi
        continue
      fi

      case "$line" in
        name:*) name="${line#name: }" ;;
        description:*) description="${line#description: }" ;;
        mode:*) mode="${line#mode: }" ;;
        model_class:*) model_class="${line#model_class: }" ;;
      esac
      continue
    fi

    body="$body$line
"
  done < "$file"

  if [ -z "$name" ] || [ -z "$description" ] || [ -z "$mode" ]; then
    echo "Invalid canonical agent: $file" >&2
    exit 1
  fi
}

render_opencode() {
  dest="$OPENCODE_AGENTS_DIR/$name.md"
  if ! can_write_generated "$dest"; then
    return 0
  fi

  if [ "$mode" = "read-only" ]; then
    permission='permission:
  edit: deny'
  else
    permission='permission:
  edit: allow'
  fi

  {
    managed_header
    printf '%s\n' '---'
    printf 'description: %s\n' "$description"
    printf '%s\n' 'mode: subagent'
    printf '%s\n' "$permission"
    printf '%s\n' '---'
    printf '\n%s' "$body"
  } > "$dest"
}

render_claude() {
  dest="$CLAUDE_AGENTS_DIR/$name.md"
  if ! can_write_generated "$dest"; then
    return 0
  fi

  if [ "$mode" = "read-only" ]; then
    tools="Read, Grep, Glob, Bash"
    permission_mode="plan"
  else
    tools="Read, Grep, Glob, Bash, Edit, MultiEdit, Write"
    permission_mode="default"
  fi

  {
    managed_header
    printf '%s\n' '---'
    printf 'name: %s\n' "$name"
    printf 'description: %s\n' "$description"
    printf 'tools: %s\n' "$tools"
    printf 'permissionMode: %s\n' "$permission_mode"
    printf '%s\n' '---'
    printf '\n%s' "$body"
  } > "$dest"
}

render_codex() {
  dest="$CODEX_AGENTS_DIR/$name.toml"
  if ! can_write_generated "$dest"; then
    return 0
  fi

  if [ "$mode" = "read-only" ]; then
    sandbox_mode="read-only"
  else
    sandbox_mode="workspace-write"
  fi

  if [ "$model_class" = "fast" ]; then
    reasoning="medium"
  else
    reasoning="high"
  fi

  {
    managed_header
    printf 'name = "%s"\n' "$name"
    printf 'description = "%s"\n' "$description"
    printf 'sandbox_mode = "%s"\n' "$sandbox_mode"
    printf 'model_reasoning_effort = "%s"\n' "$reasoning"
    printf 'developer_instructions = """\n%s"""\n' "$body"
  } > "$dest"
}

for file in "$AGENTS_DIR"/*.md; do
  parse_agent "$file"
  render_opencode
  render_claude
  render_codex
  echo "Rendered agent $name"
done
